metadata:
  favicon: ''
  code: ''
  title: Firebase Realtime DB Dashboard
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
